<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2020-11-23" />

<title>Final Report</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="site_libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="final_report.html">Final Report</a>
</li>
<li>
  <a href="https://fw2260.shinyapps.io/data_explorer/">Play with our game data!</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Contact Us
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:&lt;yj2622@cumc.columbia.edu&gt;">Ying Jin</a>
    </li>
    <li>
      <a href="mailto:&lt;tnn2113@cumc.columbia.edu&gt;">Tu Nguyen</a>
    </li>
    <li>
      <a href="mailto:&lt;ps3195@cumc.columbia.edu&gt;">Pengyuan Su</a>
    </li>
    <li>
      <a href="mailto:&lt;fw2260@columbia.edu&gt;">Lily Wang</a>
    </li>
    <li>
      <a href="mailto:&lt;hy2669@cumc.columbia.edu&gt;">Haoyang Yi</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://github.com/fw2260/p8105_final_project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final Report</h1>
<h4 class="date">11/23/2020</h4>

</div>


<style type="text/css">

h1.title {
  font-size: 40px;
  font-family: 'Abel', sans-serif;
  color: #003399;
}
h1 { /* Header 1 */
  font-size: 36px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 30px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 22px;
  color: DarkBlue;
}
h4 {/* Header 4 */
  font-size: 18px;
  color: DarkBlue;
}
</style>
<p><br></p>
<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Video games have been around for decades, providing entertainment for children and adults alike. They have been involved significantly from the early days of computer games and the early versions of Nintendo and Atari. As technology continues to improve, so do video games. Video game creation has become increasingly complicated, and the cost of creating a game to run one of the major consoles has risen with this greater complexity.</p>
<p>No longer just a niche entertainment medium, gaming has rapidly become the largest sector in terms of production and marketing. In fact, it is larger than the movie and music industry combined, and it is still growing. There are currently more than 2.5 billion gamers across the world. Analysts reported that in 2019, the gaming business was estimated to generate $152.1 billion, in which console was the second fastest-growing gaming platform, only after mobile gaming (<a href="https://newzoo.com/insights/articles/global-games-market-reaches-137-9-billion-in-2018-mobile-games-take-half/">source</a>). Since the 2000’s, three major console-developing companies have dominated the console market: Nintendo, Sony, and Microsoft. In this project, we are going to analyze the 2001-2020 global games market per console from these three companies, and learn about the various factors that influence their total revenues.</p>
<p><br></p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial Questions</h2>
<p>In contrast to the questions we initially posed in our proposal, we decided to focus on the three major console developers and factors influencing their total sales. In other words, for games released on consoles developed by Nintendo, Sony, and Microsoft, we want to know separately:</p>
<ul>
<li><p>How do the sales of games change over time?</p></li>
<li><p>What is the most popular/profitable game genre on each companies’ consoles?</p></li>
<li><p>Is there an association between critic scores and game sales? In which direction?</p></li>
<li><p>Does the number of consoles the games are released on influence their sales?</p></li>
</ul>
<p><br></p>
</div>
<div id="data-collection" class="section level2">
<h2>Data Collection</h2>
<p>We initially proposed to scrape most of our data from all 180 pages of games on <a href="https://www.metacritic.com/browse/games/score/metascore/all/all/filtered?view=detailed&amp;page=0">Metacritic</a> and merge them with sales data from <a href="https://www.vgchartz.com/games/games.php?name=&amp;keyword=&amp;console=&amp;region=All&amp;developer=&amp;publisher=&amp;goty_year=&amp;genre=Action&amp;boxart=Both&amp;banner=Both&amp;ownership=Both&amp;showmultiplat=No&amp;results=200&amp;order=TotalSales&amp;showtotalsales=0&amp;showtotalsales=1&amp;showpublisher=0&amp;showpublisher=1&amp;showvgchartzscore=0&amp;shownasales=0&amp;shownasales=1&amp;showdeveloper=0&amp;showdeveloper=1&amp;showcriticscore=0&amp;showcriticscore=1&amp;showpalsales=0&amp;showpalsales=1&amp;showreleasedate=0&amp;showreleasedate=1&amp;showuserscore=0&amp;showuserscore=1&amp;showjapansales=0&amp;showjapansales=1&amp;showlastupdate=0&amp;showothersales=0&amp;showothersales=1&amp;showshipped=0">VGChartz</a>. Metacritic is a well-known review aggregate site and is relatively transparent with its methodology for gathering critic reviews but does not contain information on sales. VGChartz is a video game sales tracking website that provides weekly sales figures of console software and hardware by region. According to their methodology page, they produce their estimates by extrapolating from retail sampling and trends, and regularly compare them to official shipment figures and figures estimated by regional trackers.</p>
<p>In an arduous process of figuring out how to scrape information such as genre that was only listed on the individual detail page of each game and repeatedly running into HTTP connection errors on Metacritic, we found and utilized the <code>polite</code> package to safely scrape the data without overwhelming the website. However, because some pages simply did not exist and we had ~18,000 games to scrape, the entire scraping process took over 24 hours to complete. The sales data from VGChartz was scraped relatively easily without the need of the <code>polite</code> package.</p>
<p>Unfortunately, after merging, our ~18,000 entries were reduced to ~2,500. We then realized that this reduction was because the two sites named many of the game titles slightly differently, and that Metacritic would list different versions of a game as separate entries while VGChartz grouped them together into one, resulting in many games that could not be merged as is. Simply dropping those entries from our dataset would be invalid, but recoding the inconsistencies manually would be entirely too time-consuming, so we decided to obtain our dataset mainly from VGChartz, possibly at the expense of having accurate critic review scores. All of the code we’ve written up to this point can be found in its own folder <a href="https://github.com/fw2260/p8105_final_project/tree/main/old">here</a>.</p>
<p>Thus our final dataset comes mainly from VGChartz, with some critic scores from the dataset mentioned above from Metacritic. Based on the raw dataset, we also created some other new columns.</p>
<p>The key steps for data cleaning are:</p>
<ul>
<li><p>Only keep games released on consoles by Nintendo, Sony or Microsoft using <code>filter</code>;</p></li>
<li><p>Get <code>critic_score</code> from the previously scraped Metacritic dataset using <code>left_join</code> by <code>title</code> and <code>console</code>;</p></li>
<li><p>Obtain the year the game was released from <code>release_date</code> using <code>separate</code>;</p></li>
<li><p>Add a new column, <code>console_developer</code>, which indicates the developer of the console (Nintendo, Sony, or Microsoft);</p></li>
<li><p>Add another new column, <code>n_platforms</code>, which shows the number of consoles the game was released on.</p></li>
</ul>
<p>After dropping NAs, there are 7340 rows and 14 columns in our final dataset.</p>
<p>Important variables include:</p>
<ul>
<li><p><code>title</code>: unique title of each game</p></li>
<li><p><code>console</code>: platform on which the game was released or is playable (i.e. Switch, PS4, etc.)</p></li>
<li><p><code>console_developer</code>: company that produces the console</p></li>
<li><p><code>n_platforms</code>: number of platforms the game was released on</p></li>
<li><p><code>genre</code>: genre of the game</p></li>
<li><p><code>release_year</code>: year of the game’s release</p></li>
<li><p><code>critic_score</code>: aggregate critic review score compiled by VGChartz and Metacritic</p></li>
<li><p><code>total_sale</code>: global revenues (million $) the game earned on that particular console</p></li>
</ul>
<p>The first ten rows of the dataset is as follow:</p>
<pre class="r"><code>head(games_df) %&gt;% 
  knitr::kable(format = &quot;html&quot;, col.names = colnames(games_df), align=&quot;c&quot;) %&gt;%
  kableExtra::kable_styling(&quot;striped&quot;, &quot;hover&quot;, row_label_position = &quot;c&quot;) %&gt;%
  kableExtra::scroll_box(width = &quot;100%&quot;, height = &quot;200px&quot;)</code></pre>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:200px; overflow-x: scroll; width:100%; ">
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
title
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
console
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
console_developer
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
n_platforms
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
genre
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
release_year
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
publisher
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
developer
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
critic_score
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
total_sale
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
na_sale
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
pal_sale
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
japan_sale
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
other_sale
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Grand Theft Auto: San Andreas
</td>
<td style="text-align:center;">
PlayStation 2
</td>
<td style="text-align:center;">
Sony
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2004
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
Rockstar North
</td>
<td style="text-align:center;">
9.5
</td>
<td style="text-align:center;">
20.81
</td>
<td style="text-align:center;">
9.43
</td>
<td style="text-align:center;">
0.40
</td>
<td style="text-align:center;">
0.41
</td>
<td style="text-align:center;">
10.57
</td>
</tr>
<tr>
<td style="text-align:center;">
Grand Theft Auto V
</td>
<td style="text-align:center;">
PlayStation 3
</td>
<td style="text-align:center;">
Sony
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2013
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
Rockstar North
</td>
<td style="text-align:center;">
9.4
</td>
<td style="text-align:center;">
20.32
</td>
<td style="text-align:center;">
6.37
</td>
<td style="text-align:center;">
9.85
</td>
<td style="text-align:center;">
0.99
</td>
<td style="text-align:center;">
3.12
</td>
</tr>
<tr>
<td style="text-align:center;">
Grand Theft Auto V
</td>
<td style="text-align:center;">
PlayStation 4
</td>
<td style="text-align:center;">
Sony
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2014
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
Rockstar North
</td>
<td style="text-align:center;">
9.7
</td>
<td style="text-align:center;">
19.39
</td>
<td style="text-align:center;">
6.06
</td>
<td style="text-align:center;">
9.71
</td>
<td style="text-align:center;">
0.60
</td>
<td style="text-align:center;">
3.02
</td>
</tr>
<tr>
<td style="text-align:center;">
Grand Theft Auto: Vice City
</td>
<td style="text-align:center;">
PlayStation 2
</td>
<td style="text-align:center;">
Sony
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2002
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
Rockstar North
</td>
<td style="text-align:center;">
9.6
</td>
<td style="text-align:center;">
16.15
</td>
<td style="text-align:center;">
8.41
</td>
<td style="text-align:center;">
5.49
</td>
<td style="text-align:center;">
0.47
</td>
<td style="text-align:center;">
1.78
</td>
</tr>
<tr>
<td style="text-align:center;">
Grand Theft Auto III
</td>
<td style="text-align:center;">
PlayStation 2
</td>
<td style="text-align:center;">
Sony
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2001
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
DMA Design
</td>
<td style="text-align:center;">
9.5
</td>
<td style="text-align:center;">
13.10
</td>
<td style="text-align:center;">
6.99
</td>
<td style="text-align:center;">
4.51
</td>
<td style="text-align:center;">
0.30
</td>
<td style="text-align:center;">
1.30
</td>
</tr>
<tr>
<td style="text-align:center;">
Grand Theft Auto IV
</td>
<td style="text-align:center;">
Xbox 360
</td>
<td style="text-align:center;">
Microsoft
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
action
</td>
<td style="text-align:center;">
2008
</td>
<td style="text-align:center;">
Rockstar Games
</td>
<td style="text-align:center;">
Rockstar North
</td>
<td style="text-align:center;">
10.0
</td>
<td style="text-align:center;">
11.09
</td>
<td style="text-align:center;">
6.80
</td>
<td style="text-align:center;">
3.11
</td>
<td style="text-align:center;">
0.14
</td>
<td style="text-align:center;">
1.04
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
</div>
<div id="exploratory-analyses" class="section level2">
<h2>Exploratory Analyses</h2>
<div id="global-sales-and-number-of-games-released-across-the-years" class="section level3 tabset">
<h3>Global sales and Number of games released across the years</h3>
<div id="all-consoles" class="section level4">
<h4>All Consoles</h4>
<pre class="r"><code>totalsale = games_df %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    totalsale = sum(total_sale)
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = totalsale)) +
  geom_col(color = &quot;purple4&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Total Sale (million USD)&quot;)

totalsale_plotly = ggplotly(totalsale)

totalcount = games_df %&gt;% 
 group_by(release_year) %&gt;% 
  summarize(
    count = n()
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = count)) +
  geom_col(color = &quot;lightseagreen&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Number of Games&quot;)

totalcount_plotly = ggplotly(totalcount)

subplot(totalsale_plotly, totalcount_plotly, titleX = TRUE, titleY = TRUE, margin = 0.1)</code></pre>
<div id="htmlwidget-b9e97f82e6f39840ea55" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-b9e97f82e6f39840ea55">{"x":{"data":[{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[279.66,313.65,323.37,319.77,363.18,426.12,510.26,545.35,511.59,428.95,425.83,243.67,286.08,232.94,193.44,201.94,171.32,125.58,1.35,0.59],"text":["release_year: 2001<br />totalsale: 279.66","release_year: 2002<br />totalsale: 313.65","release_year: 2003<br />totalsale: 323.37","release_year: 2004<br />totalsale: 319.77","release_year: 2005<br />totalsale: 363.18","release_year: 2006<br />totalsale: 426.12","release_year: 2007<br />totalsale: 510.26","release_year: 2008<br />totalsale: 545.35","release_year: 2009<br />totalsale: 511.59","release_year: 2010<br />totalsale: 428.95","release_year: 2011<br />totalsale: 425.83","release_year: 2012<br />totalsale: 243.67","release_year: 2013<br />totalsale: 286.08","release_year: 2014<br />totalsale: 232.94","release_year: 2015<br />totalsale: 193.44","release_year: 2016<br />totalsale: 201.94","release_year: 2017<br />totalsale: 171.32","release_year: 2018<br />totalsale: 125.58","release_year: 2019<br />totalsale:   1.35","release_year: 2020<br />totalsale:   0.59"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(85,26,139,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[308,564,569,521,613,527,584,620,586,440,422,270,199,199,193,220,249,233,18,5],"text":["release_year: 2001<br />count: 308","release_year: 2002<br />count: 564","release_year: 2003<br />count: 569","release_year: 2004<br />count: 521","release_year: 2005<br />count: 613","release_year: 2006<br />count: 527","release_year: 2007<br />count: 584","release_year: 2008<br />count: 620","release_year: 2009<br />count: 586","release_year: 2010<br />count: 440","release_year: 2011<br />count: 422","release_year: 2012<br />count: 270","release_year: 2013<br />count: 199","release_year: 2014<br />count: 199","release_year: 2015<br />count: 193","release_year: 2016<br />count: 220","release_year: 2017<br />count: 249","release_year: 2018<br />count: 233","release_year: 2019<br />count:  18","release_year: 2020<br />count:   5"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(32,178,170,1)"}},"showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null}],"layout":{"xaxis":{"domain":[0,0.4],"automargin":true,"type":"linear","autorange":false,"range":[1999.555,2021.445],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"xaxis2":{"domain":[0.6,1],"automargin":true,"type":"linear","autorange":false,"range":[1999.555,2021.445],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis2":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-31,651],"tickmode":"array","ticktext":["0","200","400","600"],"tickvals":[0,200,400,600],"categoryorder":"array","categoryarray":["0","200","400","600"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x2","title":{"text":"Number of Games","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-27.2675,572.6175],"tickmode":"array","ticktext":["0","200","400"],"tickvals":[0,200,400],"categoryorder":"array","categoryarray":["0","200","400"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Total Sale (million USD)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"annotations":[],"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.4,"y0":0,"y1":1},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.6,"x1":1,"y0":0,"y1":1}],"images":[],"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"showlegend":false,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"attrs":{"b509689a28f4":{"x":{},"y":{},"type":"bar"},"b50953a65f32":{"x":{},"y":{},"type":"bar"}},"source":"A","config":{"doubleClick":"reset","showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>The left bar graph shows the cumulative global revenues (in million USD) of each game by release year from 2001 and 2020 on the three companies’ platforms. In other words, it is showing how much the games made (from its release year to present) by their release year. <em>Note: this graph is NOT showing annual sales of games.</em> The right graph shows the number of video games released on these platforms in the same period.</p>
<p>The video game industry increases at a rapid rate after 2001 with a drastic increase in number of games released each year and the high volume reaches its peak in 2008, with 620 games published on these major platforms. After 2008, both cumulative sales and number of games released decreases over time.</p>
<p>Note that the number of game releases from the three companies in 2019 is only 18 and in 2020 is 5, which is not the case in reality. Therefore, we consider data in 2019 and 2020 to be inaccurate and will exclude them in our statistical analyses.</p>
<p><br></p>
</div>
<div id="nintendo" class="section level4">
<h4>Nintendo</h4>
<pre class="r"><code>totalsale = games_df %&gt;% 
  filter(console_developer == &quot;Nintendo&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    totalsale = sum(total_sale)
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = totalsale)) +
  geom_col(color = &quot;navyblue&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Total Sale (million USD)&quot;)

totalsale_plotly = ggplotly(totalsale)

totalcount = games_df %&gt;% 
  filter(console_developer == &quot;Nintendo&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    count = n()
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = count)) +
  geom_col(color = &quot;darkred&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Number of Games&quot;)

totalcount_plotly = ggplotly(totalcount)

subplot(totalsale_plotly, totalcount_plotly, titleX = TRUE, titleY = TRUE, margin = 0.1)</code></pre>
<div id="htmlwidget-661e771b1d2e89ac1bba" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-661e771b1d2e89ac1bba">{"x":{"data":[{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019],"y":[82.42,96.59,101.62,83.32,129.06,223,254.8,231.58,234.35,134.25,128.67,54.14,71.06,46.45,34.85,39.29,16.51,2.26,0.22],"text":["release_year: 2001<br />totalsale:  82.42","release_year: 2002<br />totalsale:  96.59","release_year: 2003<br />totalsale: 101.62","release_year: 2004<br />totalsale:  83.32","release_year: 2005<br />totalsale: 129.06","release_year: 2006<br />totalsale: 223.00","release_year: 2007<br />totalsale: 254.80","release_year: 2008<br />totalsale: 231.58","release_year: 2009<br />totalsale: 234.35","release_year: 2010<br />totalsale: 134.25","release_year: 2011<br />totalsale: 128.67","release_year: 2012<br />totalsale:  54.14","release_year: 2013<br />totalsale:  71.06","release_year: 2014<br />totalsale:  46.45","release_year: 2015<br />totalsale:  34.85","release_year: 2016<br />totalsale:  39.29","release_year: 2017<br />totalsale:  16.51","release_year: 2018<br />totalsale:   2.26","release_year: 2019<br />totalsale:   0.22"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,128,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019],"y":[94,251,211,181,181,182,238,264,262,142,136,59,48,35,41,38,20,8,3],"text":["release_year: 2001<br />count:  94","release_year: 2002<br />count: 251","release_year: 2003<br />count: 211","release_year: 2004<br />count: 181","release_year: 2005<br />count: 181","release_year: 2006<br />count: 182","release_year: 2007<br />count: 238","release_year: 2008<br />count: 264","release_year: 2009<br />count: 262","release_year: 2010<br />count: 142","release_year: 2011<br />count: 136","release_year: 2012<br />count:  59","release_year: 2013<br />count:  48","release_year: 2014<br />count:  35","release_year: 2015<br />count:  41","release_year: 2016<br />count:  38","release_year: 2017<br />count:  20","release_year: 2018<br />count:   8","release_year: 2019<br />count:   3"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(139,0,0,1)"}},"showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null}],"layout":{"xaxis":{"domain":[0,0.4],"automargin":true,"type":"linear","autorange":false,"range":[1999.605,2020.395],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"xaxis2":{"domain":[0.6,1],"automargin":true,"type":"linear","autorange":false,"range":[1999.605,2020.395],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis2":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-13.2,277.2],"tickmode":"array","ticktext":["0","100","200"],"tickvals":[0,100,200],"categoryorder":"array","categoryarray":["0","100","200"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x2","title":{"text":"Number of Games","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-12.74,267.54],"tickmode":"array","ticktext":["0","100","200"],"tickvals":[0,100,200],"categoryorder":"array","categoryarray":["0","100","200"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Total Sale (million USD)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"annotations":[],"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.4,"y0":0,"y1":1},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.6,"x1":1,"y0":0,"y1":1}],"images":[],"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"showlegend":false,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"attrs":{"b5094e79aa8c":{"x":{},"y":{},"type":"bar"},"b50969177c7f":{"x":{},"y":{},"type":"bar"}},"source":"A","config":{"doubleClick":"reset","showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>We can see a similar trend for <strong>Nintendo</strong> and <strong>Microsoft</strong>.</p>
</div>
<div id="microsoft" class="section level4">
<h4>Microsoft</h4>
<pre class="r"><code>totalsale = games_df %&gt;% 
  filter(console_developer == &quot;Microsoft&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    totalsale = sum(total_sale)
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = totalsale)) +
  geom_col(color = &quot;navyblue&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Total Sale (million USD)&quot;)

totalsale_plotly = ggplotly(totalsale)

totalcount = games_df %&gt;% 
  filter(console_developer == &quot;Microsoft&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    count = n()
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = count)) +
  geom_col(color = &quot;darkred&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Number of Games&quot;)

totalcount_plotly = ggplotly(totalcount)

subplot(totalsale_plotly, totalcount_plotly, titleX = TRUE, titleY = TRUE, margin = 0.1)</code></pre>
<div id="htmlwidget-dc1f6a141be4d276260d" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-dc1f6a141be4d276260d">{"x":{"data":[{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],"y":[22.27,41.92,50.79,57.8,49.8,49.96,96.55,136.34,117.67,141.2,136.66,83.92,87.58,62.15,52.04,52.3,39.2,31.28],"text":["release_year: 2001<br />totalsale:  22.27","release_year: 2002<br />totalsale:  41.92","release_year: 2003<br />totalsale:  50.79","release_year: 2004<br />totalsale:  57.80","release_year: 2005<br />totalsale:  49.80","release_year: 2006<br />totalsale:  49.96","release_year: 2007<br />totalsale:  96.55","release_year: 2008<br />totalsale: 136.34","release_year: 2009<br />totalsale: 117.67","release_year: 2010<br />totalsale: 141.20","release_year: 2011<br />totalsale: 136.66","release_year: 2012<br />totalsale:  83.92","release_year: 2013<br />totalsale:  87.58","release_year: 2014<br />totalsale:  62.15","release_year: 2015<br />totalsale:  52.04","release_year: 2016<br />totalsale:  52.30","release_year: 2017<br />totalsale:  39.20","release_year: 2018<br />totalsale:  31.28"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,128,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],"y":[32,120,164,139,174,117,115,137,122,134,130,82,58,58,51,56,74,85],"text":["release_year: 2001<br />count:  32","release_year: 2002<br />count: 120","release_year: 2003<br />count: 164","release_year: 2004<br />count: 139","release_year: 2005<br />count: 174","release_year: 2006<br />count: 117","release_year: 2007<br />count: 115","release_year: 2008<br />count: 137","release_year: 2009<br />count: 122","release_year: 2010<br />count: 134","release_year: 2011<br />count: 130","release_year: 2012<br />count:  82","release_year: 2013<br />count:  58","release_year: 2014<br />count:  58","release_year: 2015<br />count:  51","release_year: 2016<br />count:  56","release_year: 2017<br />count:  74","release_year: 2018<br />count:  85"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(139,0,0,1)"}},"showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null}],"layout":{"xaxis":{"domain":[0,0.4],"automargin":true,"type":"linear","autorange":false,"range":[1999.655,2019.345],"tickmode":"array","ticktext":["2000","2005","2010","2015"],"tickvals":[2000,2005,2010,2015],"categoryorder":"array","categoryarray":["2000","2005","2010","2015"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"xaxis2":{"domain":[0.6,1],"automargin":true,"type":"linear","autorange":false,"range":[1999.655,2019.345],"tickmode":"array","ticktext":["2000","2005","2010","2015"],"tickvals":[2000,2005,2010,2015],"categoryorder":"array","categoryarray":["2000","2005","2010","2015"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis2":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-8.7,182.7],"tickmode":"array","ticktext":["0","50","100","150"],"tickvals":[0,50,100,150],"categoryorder":"array","categoryarray":["0","50","100","150"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x2","title":{"text":"Number of Games","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-7.06,148.26],"tickmode":"array","ticktext":["0","50","100"],"tickvals":[0,50,100],"categoryorder":"array","categoryarray":["0","50","100"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Total Sale (million USD)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"annotations":[],"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.4,"y0":0,"y1":1},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.6,"x1":1,"y0":0,"y1":1}],"images":[],"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"showlegend":false,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"attrs":{"b50953aeaa72":{"x":{},"y":{},"type":"bar"},"b509204c2730":{"x":{},"y":{},"type":"bar"}},"source":"A","config":{"doubleClick":"reset","showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>We can see a similar trend for <strong>Nintendo</strong> and <strong>Microsoft</strong>.</p>
</div>
<div id="sony" class="section level4">
<h4>Sony</h4>
<pre class="r"><code>totalsale = games_df %&gt;% 
  filter(console_developer == &quot;Sony&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    totalsale = sum(total_sale)
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = totalsale)) +
  geom_col(color = &quot;navyblue&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Total Sale (million USD)&quot;)

totalsale_plotly = ggplotly(totalsale)

totalcount = games_df %&gt;% 
  filter(console_developer == &quot;Sony&quot;) %&gt;% 
  group_by(release_year) %&gt;% 
  summarize(
    count = n()
  ) %&gt;% 
  drop_na() %&gt;% 
  ggplot(aes(x = release_year, y = count)) +
  geom_col(color = &quot;darkred&quot;, fill = &quot;white&quot;) +
  labs(x = &quot;Release Year&quot;, y = &quot;Number of Games&quot;)

totalcount_plotly = ggplotly(totalcount)

subplot(totalsale_plotly, totalcount_plotly, titleX = TRUE, titleY = TRUE, margin = 0.1)</code></pre>
<div id="htmlwidget-9f4e7533d9e1e9c71c5e" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-9f4e7533d9e1e9c71c5e">{"x":{"data":[{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[174.97,175.14,170.96,178.65,184.32,153.16,158.91,177.43,159.57,153.5,160.5,105.61,127.44,124.34,106.55,110.35,115.61,92.04,1.13,0.59],"text":["release_year: 2001<br />totalsale: 174.97","release_year: 2002<br />totalsale: 175.14","release_year: 2003<br />totalsale: 170.96","release_year: 2004<br />totalsale: 178.65","release_year: 2005<br />totalsale: 184.32","release_year: 2006<br />totalsale: 153.16","release_year: 2007<br />totalsale: 158.91","release_year: 2008<br />totalsale: 177.43","release_year: 2009<br />totalsale: 159.57","release_year: 2010<br />totalsale: 153.50","release_year: 2011<br />totalsale: 160.50","release_year: 2012<br />totalsale: 105.61","release_year: 2013<br />totalsale: 127.44","release_year: 2014<br />totalsale: 124.34","release_year: 2015<br />totalsale: 106.55","release_year: 2016<br />totalsale: 110.35","release_year: 2017<br />totalsale: 115.61","release_year: 2018<br />totalsale:  92.04","release_year: 2019<br />totalsale:   1.13","release_year: 2020<br />totalsale:   0.59"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,128,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091,0.900000000000091],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020],"y":[182,193,194,201,258,228,231,219,202,164,156,129,93,106,101,126,155,140,15,5],"text":["release_year: 2001<br />count: 182","release_year: 2002<br />count: 193","release_year: 2003<br />count: 194","release_year: 2004<br />count: 201","release_year: 2005<br />count: 258","release_year: 2006<br />count: 228","release_year: 2007<br />count: 231","release_year: 2008<br />count: 219","release_year: 2009<br />count: 202","release_year: 2010<br />count: 164","release_year: 2011<br />count: 156","release_year: 2012<br />count: 129","release_year: 2013<br />count:  93","release_year: 2014<br />count: 106","release_year: 2015<br />count: 101","release_year: 2016<br />count: 126","release_year: 2017<br />count: 155","release_year: 2018<br />count: 140","release_year: 2019<br />count:  15","release_year: 2020<br />count:   5"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,255,255,1)","line":{"width":1.88976377952756,"color":"rgba(139,0,0,1)"}},"showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null}],"layout":{"xaxis":{"domain":[0,0.4],"automargin":true,"type":"linear","autorange":false,"range":[1999.555,2021.445],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"xaxis2":{"domain":[0.6,1],"automargin":true,"type":"linear","autorange":false,"range":[1999.555,2021.445],"tickmode":"array","ticktext":["2000","2005","2010","2015","2020"],"tickvals":[2000,2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2000","2005","2010","2015","2020"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y2","title":{"text":"Release Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis2":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-12.9,270.9],"tickmode":"array","ticktext":["0","100","200"],"tickvals":[0,100,200],"categoryorder":"array","categoryarray":["0","100","200"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x2","title":{"text":"Number of Games","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-9.216,193.536],"tickmode":"array","ticktext":["0","50","100","150"],"tickvals":[0,50,100,150],"categoryorder":"array","categoryarray":["0","50","100","150"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Total Sale (million USD)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"annotations":[],"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.4,"y0":0,"y1":1},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.6,"x1":1,"y0":0,"y1":1}],"images":[],"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":40.1826484018265,"l":43.1050228310502},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"showlegend":false,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895}},"hovermode":"closest","barmode":"relative"},"attrs":{"b509214de63":{"x":{},"y":{},"type":"bar"},"b5096372a95a":{"x":{},"y":{},"type":"bar"}},"source":"A","config":{"doubleClick":"reset","showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>However, for <strong>Sony</strong>, it’s a different story. Cumulative sales of games released earlier starts high and those released later keeps decreasing.</p>
</div>
</div>
<div id="global-sales-of-games-per-genre" class="section level3">
<h3>Global sales of games per genre</h3>
<pre class="r"><code>genre_sale_plot = 
  games_df %&gt;% 
  group_by(genre) %&gt;% 
  mutate(total = sum(total_sale)) %&gt;% 
  ungroup() %&gt;% 
  mutate(
    genre = fct_reorder(genre, desc(total))) %&gt;% 
  group_by(genre, console_developer) %&gt;% 
  summarise(
    sum_sale = sum(total_sale)
  ) %&gt;% 
  ggplot(aes(x = genre, y = sum_sale, fill = console_developer)) +
  geom_bar(stat = &quot;identity&quot;, alpha = .7) +
  theme(
    axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 1, size = 8),
    legend.position = &quot;bottom&quot;,
    legend.text = element_text(size = 8)) +
  labs(x = &quot;Genre&quot;, y = &quot;Total Sale (million USD)&quot;, fill = &quot;Developer&quot;)

ggplotly(genre_sale_plot) </code></pre>
<div id="htmlwidget-c4cfe447cc18a6b8e675" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-c4cfe447cc18a6b8e675">{"x":{"data":[{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[783.81,732.29,470.32,538.06,388.17,439.54,381.06,225.32,218.42,191.25,112.15,71.78,43.04],"x":[1,2,3,4,5,6,7,8,9,10,11,12,13],"y":[219.28,235.05,403.49,100.61,103.21,26.3,53.45,59.67,34.13,20.04,40.53,1.87,11.8],"text":["genre: sports<br />sum_sale: 219.28<br />console_developer: Microsoft","genre: action<br />sum_sale: 235.05<br />console_developer: Microsoft","genre: shooting<br />sum_sale: 403.49<br />console_developer: Microsoft","genre: role_playing<br />sum_sale: 100.61<br />console_developer: Microsoft","genre: racing<br />sum_sale: 103.21<br />console_developer: Microsoft","genre: platform<br />sum_sale:  26.30<br />console_developer: Microsoft","genre: miscellaneous<br />sum_sale:  53.45<br />console_developer: Microsoft","genre: fighting<br />sum_sale:  59.67<br />console_developer: Microsoft","genre: adventure<br />sum_sale:  34.13<br />console_developer: Microsoft","genre: simulation<br />sum_sale:  20.04<br />console_developer: Microsoft","genre: action_adventure<br />sum_sale:  40.53<br />console_developer: Microsoft","genre: puzzle<br />sum_sale:   1.87<br />console_developer: Microsoft","genre: strategy<br />sum_sale:  11.80<br />console_developer: Microsoft"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(68,1,84,0.7)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Microsoft","legendgroup":"Microsoft","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[481.72,580.94,410.72,247.37,247.75,136.1,110.41,163.69,81.31,45.58,97.39,11.08,16.71],"x":[1,2,3,4,5,6,7,8,9,10,11,12,13],"y":[302.09,151.35,59.6,290.69,140.42,303.44,270.65,61.63,137.11,145.67,14.76,60.7,26.33],"text":["genre: sports<br />sum_sale: 302.09<br />console_developer: Nintendo","genre: action<br />sum_sale: 151.35<br />console_developer: Nintendo","genre: shooting<br />sum_sale:  59.60<br />console_developer: Nintendo","genre: role_playing<br />sum_sale: 290.69<br />console_developer: Nintendo","genre: racing<br />sum_sale: 140.42<br />console_developer: Nintendo","genre: platform<br />sum_sale: 303.44<br />console_developer: Nintendo","genre: miscellaneous<br />sum_sale: 270.65<br />console_developer: Nintendo","genre: fighting<br />sum_sale:  61.63<br />console_developer: Nintendo","genre: adventure<br />sum_sale: 137.11<br />console_developer: Nintendo","genre: simulation<br />sum_sale: 145.67<br />console_developer: Nintendo","genre: action_adventure<br />sum_sale:  14.76<br />console_developer: Nintendo","genre: puzzle<br />sum_sale:  60.70<br />console_developer: Nintendo","genre: strategy<br />sum_sale:  26.33<br />console_developer: Nintendo"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(33,144,140,0.7)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Nintendo","legendgroup":"Nintendo","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999,0.899999999999999],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[1,2,3,4,5,6,7,8,9,10,11,12,13],"y":[481.72,580.94,410.72,247.37,247.75,136.1,110.41,163.69,81.31,45.58,97.39,11.08,16.71],"text":["genre: sports<br />sum_sale: 481.72<br />console_developer: Sony","genre: action<br />sum_sale: 580.94<br />console_developer: Sony","genre: shooting<br />sum_sale: 410.72<br />console_developer: Sony","genre: role_playing<br />sum_sale: 247.37<br />console_developer: Sony","genre: racing<br />sum_sale: 247.75<br />console_developer: Sony","genre: platform<br />sum_sale: 136.10<br />console_developer: Sony","genre: miscellaneous<br />sum_sale: 110.41<br />console_developer: Sony","genre: fighting<br />sum_sale: 163.69<br />console_developer: Sony","genre: adventure<br />sum_sale:  81.31<br />console_developer: Sony","genre: simulation<br />sum_sale:  45.58<br />console_developer: Sony","genre: action_adventure<br />sum_sale:  97.39<br />console_developer: Sony","genre: puzzle<br />sum_sale:  11.08<br />console_developer: Sony","genre: strategy<br />sum_sale:  16.71<br />console_developer: Sony"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(253,231,37,0.7)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Sony","legendgroup":"Sony","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.2283105022831,"r":7.30593607305936,"b":63.4560426645059,"l":48.9497716894977},"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,13.6],"tickmode":"array","ticktext":["sports","action","shooting","role_playing","racing","platform","miscellaneous","fighting","adventure","simulation","action_adventure","puzzle","strategy"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13],"categoryorder":"array","categoryarray":["sports","action","shooting","role_playing","racing","platform","miscellaneous","fighting","adventure","simulation","action_adventure","puzzle","strategy"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":10.6268161062682},"tickangle":-70,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"Genre","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-50.1545,1053.2445],"tickmode":"array","ticktext":["0","250","500","750","1000"],"tickvals":[0,250,500,750,1000],"categoryorder":"array","categoryarray":["0","250","500","750","1000"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":3.65296803652968,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"Total Sale (million USD)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":10.6268161062682},"y":0.913385826771654},"annotations":[{"text":"Developer","x":1.02,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"left","yanchor":"bottom","legendTitle":true}],"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"b5097efe9f17":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"b5097efe9f17","visdat":{"b5097efe9f17":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p><strong>Sports</strong> games have been around since the beginning of gaming, and it is the most popular genre, with global sales more than 1.0 billion USD. Coming in second and third respectively are <strong>Action</strong> and <strong>Shooting</strong>, challenging the player’s reflexes and coordination.</p>
<p>The revenues of each company, however, are not the same across the genres. * <strong>Nintendo</strong> earns more profit from making games in <strong>sports</strong>, <strong>role-playing</strong>, and <strong>platform</strong>, with each of them bring back more than 290 million USD.</p>
<ul>
<li><p><strong>Sony</strong>’s best-selling genre is <strong>action</strong>, which achieves 580.94 million USD revenue between 2001 to 2020. <strong>Sports</strong> and <strong>shooting</strong> also brings huge profits to Sony, with 481.72 and 410.72 million USD, respectively.</p></li>
<li><p><strong>Microsoft</strong>, despite being the latest competitor to enter the video game industry, performs well in the <strong>shooting</strong>, <strong>sports</strong>, and <strong>action</strong> genres. The company’s highest revenue is from shooting games with 403.39 million USD.</p></li>
</ul>
<p><br></p>
</div>
<div id="relationship-between-critic-score-and-total-revenues" class="section level3">
<h3>Relationship between critic score and total revenues</h3>
<pre class="r"><code>games_df %&gt;% 
  filter(total_sale &lt; 5) %&gt;% 
  ggplot(aes(x = critic_score, y = total_sale, color = console_developer)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = &#39;lm&#39;, se = F) +
  labs(x = &quot;Critic Score&quot;, y = &quot;Total Sale (million USD)&quot;, color = &quot;Console Developer&quot;)</code></pre>
<p><img src="final_report_files/figure-html/q3-1.png" width="672" /></p>
<p>Critic consensus on a game usually has some correlation with the success of the game in the market because critic reviews may influence consumers’ decision to buy games.Based on the fitted linear regression lines, it would seem that <strong>Microsoft</strong> and <strong>Sony</strong>’s games usually has scores greater than 5/10, which means that their games have overall good quality. While for <strong>Nintendo</strong>, more of its games earned low scores from critics.</p>
<p>Generally, as critic score increases, sales of games on the three companies’ consoles all increase. What’s interesting is that <strong>Sony</strong>’s game sale increases more than the others for one unit increase in critic score and <strong>Nintendo</strong>’s increases the least.</p>
<p><br></p>
</div>
<div id="platform-availability" class="section level3">
<h3>Platform Availability</h3>
<pre class="r"><code>platform_available = 
  games_df %&gt;% 
  mutate(n_platforms = as.factor(n_platforms)) %&gt;% 
  ggplot(aes(x = n_platforms, y = log(total_sale), fill = console_developer)) +
  geom_violin(alpha = .5) +
  labs(x = &quot;\nNumber of Platforms&quot;, y = &quot;Total Sale Log(million USD)\n&quot;) +
  theme_light() +
  facet_wrap(~console_developer,nrow = 3) +
  theme(
    text = element_text(size = 9),
    legend.text = element_text(size = 9),
    axis.title.x = element_text(vjust = -0.5),
    axis.title.y = element_text(vjust = 3.5),
    legend.position = &quot;none&quot;
  )

platform_available</code></pre>
<p><img src="final_report_files/figure-html/q4-1.png" width="672" /></p>
<p>For games of <strong>Microsoft</strong> and <strong>Sony</strong>, the sales improves as the number of console increases overall. And this trend is more apparent for <strong>Sony</strong>. This means that for these two companies, more available games sells better than less available games. However, this is not the case for <strong>Nintendo</strong>. Even though there are also non-exclusive games on <strong>Nintendo</strong>’s consoles, they don’t contribute more revenue than games with less platform availability. This is unsurprising as Nintendo is known for their console-exclusive games.</p>
<p><br></p>
</div>
</div>
<div id="statistical-analyses" class="section level2">
<h2>Statistical Analyses</h2>
<div id="anova-test" class="section level3">
<h3>Anova Test</h3>
<pre class="r"><code>games_df = games_df %&gt;%
   filter(release_year &lt; 2019) %&gt;%
  mutate(
    n_platforms = 
      case_when(n_platforms == &#39;1&#39; ~ &#39;small&#39;,
                n_platforms &gt;= &#39;2&#39; &amp; n_platforms &lt;= &#39;3&#39; ~ &#39;medium&#39;,
                n_platforms &gt;= &#39;4&#39; ~ &#39;large&#39;),
    n_platforms = as.factor(n_platforms)
    ) %&gt;% 
  dplyr::select(title:genre,critic_score, total_sale)</code></pre>
<p>Using Analysis of Variance (ANOVA) we can conduct statistical comparisons among groups of our interested categorical variables: n_platforms. We further divided n_platform into 3 groups: <code>small</code> (<code>n_platforms</code> = 1), <code>medium</code> (2 &lt;= <code>n_platforms</code> &lt;= 3) and <code>large</code> (4 &lt;= <code>n_platforms</code> &lt;= 9).</p>
<p><br></p>
</div>
<div id="one-way-anova-total_sale-n_platforms" class="section level3">
<h3>1. One-way ANOVA: total_sale ~ n_platforms</h3>
<pre class="r"><code>aov_mod_1 = aov(total_sale ~ n_platforms, data = games_df)</code></pre>
<pre class="r"><code>broom::tidy(aov_mod_1)</code></pre>
<pre><code>## # A tibble: 2 x 6
##   term           df  sumsq meansq statistic     p.value
##   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 n_platforms     2   109.  54.5       13.5  0.00000141
## 2 Residuals    7314 29526.   4.04      NA   NA</code></pre>
<pre class="r"><code>multi_comp_1 = TukeyHSD(aov_mod_1)
plot(multi_comp_1)</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>With p.value &lt; 0.001, we conclude that at least two of the n_platforms groups have different average total_sales. Then Tukey’s method was performed to make pairwise comparisons. All comparisons have significant differences in mean of total_sale.</p>
<p><br></p>
</div>
<div id="conclusion" class="section level3">
<h3>2. Conclusion</h3>
<p>The ANOVA test above provides evidence that there are true differences in games sales among different groups of n_platforms. Therefore, we will include console_developer, n_platforms, critic_score as predictors in our linear regression model.</p>
<p>Similarly, we conducted ANOVA test for different levels of genre and concluded that there are true difference in global sales among different genres.</p>
<p><br></p>
</div>
<div id="linear-regression" class="section level3">
<h3>Linear Regression</h3>
<pre class="r"><code>regression_df = 
  games_df %&gt;%
  filter(total_sale &lt; 5) # cut off outliers</code></pre>
<p>Based on the boxplot of total sales, the values of total sales are heavily skewed right. In order to cut off the outliers, the dataset was filtered to only include games with total sales less than 5 million USD. Therefore any values greater than 5 are excluded for linear regression analysis.</p>
<p><br></p>
</div>
<div id="build-models" class="section level3">
<h3>1. Build Models</h3>
<p><strong>Model 1:</strong> <span class="math inline">\(total\_sale \sim console\_developer * genre + console\_developer * n\_platforms\)</span></p>
<p><strong>Model 2:</strong> <span class="math inline">\(total\_sale \sim console\_developer * genre + console\_developer * n\_platforms + console\_developer * critic\_score\)</span></p>
<p><strong>Model 3:</strong> <span class="math inline">\(total\_sale \sim console\_developer * genre + console\_developer * critic\_score\)</span></p>
<p><strong>Model 4:</strong> <span class="math inline">\(total\_sale \sim console\_developer * n\_platforms + console\_developer * critic\_score\)</span></p>
<p>Model 2 contains console_developer and all other interested predictors (genre, n_platform, critic_score), as well as interactions. While Model 1, 3, and 4 contain console_developer and only two of interested predictors and their interactions.</p>
<p><br></p>
</div>
<div id="cross-validation" class="section level3">
<h3>2. Cross validation</h3>
<p>We use <code>crossv_mc</code> method to create training and testing datasets and fit the above 4 candidate models. The violin plots below shows the distribution of <strong>RMSE</strong> values for each model:</p>
<pre class="r"><code>cv_df %&gt;% 
  dplyr::select(starts_with(&quot;rmse&quot;)) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;,
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;
  ) %&gt;% 
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()</code></pre>
<p><img src="final_report_files/figure-html/regression_rmse_compare1234-1.png" width="672" /></p>
<p>Based on the results, Model 2 has the lowest <strong>RMSE</strong>, but <strong>RMSE</strong> of Model 3 and 4 are just slightly higher than Model 2, which indicates that there’s minor improvement for adding <code>console_developer*critic_score</code> as an additional predictor. Also, there are 6 subgroups in <code>genre</code>, which makes Model 3 harder to interpret than Model 4. In this way, we decide to select <strong>Model 4</strong> as our final model.</p>
<p><br></p>
</div>
<div id="diagnosis" class="section level3">
<h3>3. Diagnosis</h3>
<p>In <strong>Model 4</strong>, we used <strong>Residuals vs Fitted Values</strong> plot to detect unequal error variance (heteroscedasticity) and outliers.</p>
<pre class="r"><code>lm4 = lm(total_sale ~ console_developer*n_platforms + console_developer*critic_score, data = regression_df)

regression_df %&gt;%
  add_predictions(lm4) %&gt;%
  add_residuals(lm4) %&gt;%
  ggplot(aes(x = pred, y = resid))+ 
  geom_point(alpha = 0.3)+
  geom_smooth(method = &#39;lm&#39;, color = &#39;red&#39;)+
  labs(x = &#39;fitted values of total_sales&#39;, y = &#39;model residuals&#39;, title = &#39;Residuals vs Fitted Values&#39;)</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>As shown in the graph, there are many outliers with residuals &gt; 3. Although the mean of residual values is close to 0 and residuals have a horizontal relationship with fitted value, the distribution of residual values is skewed. This plot indicates that our model does not have ideally distributed residuals.</p>
<p><br></p>
</div>
<div id="results" class="section level3">
<h3>4. Results</h3>
<p>The summary of the selected model: <span class="math inline">\(total\_sale \sim console\_developer * n\_platforms + console\_developer * critic\_score\)</span> is as follow:</p>
<pre class="r"><code>coe_df = broom::tidy(lm4) 

coe_df_tidy = 
  coe_df %&gt;%
  select(term, estimate, p.value) %&gt;% 
  mutate(
    term = str_replace(term, &quot;^console_developer:&quot;, &quot;Developer: &quot;),
    term = str_replace(term, &quot;^n_platforms:&quot;, &quot;Num_Consoles: &quot;),
  ) %&gt;%
  knitr::kable(digits = 3)

coe_df_tidy</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-0.801
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerNintendo
</td>
<td style="text-align:right;">
0.476
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerSony
</td>
<td style="text-align:right;">
-0.136
</td>
<td style="text-align:right;">
0.298
</td>
</tr>
<tr>
<td style="text-align:left;">
n_platformsmedium
</td>
<td style="text-align:right;">
-0.299
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
n_platformssmall
</td>
<td style="text-align:right;">
-0.265
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
critic_score
</td>
<td style="text-align:right;">
0.228
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerNintendo:n_platformsmedium
</td>
<td style="text-align:right;">
0.215
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerSony:n_platformsmedium
</td>
<td style="text-align:right;">
-0.025
</td>
<td style="text-align:right;">
0.684
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerNintendo:n_platformssmall
</td>
<td style="text-align:right;">
0.313
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerSony:n_platformssmall
</td>
<td style="text-align:right;">
-0.210
</td>
<td style="text-align:right;">
0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerNintendo:critic_score
</td>
<td style="text-align:right;">
-0.107
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
console_developerSony:critic_score
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
</tbody>
</table>
<p>According to <strong>Model 4</strong>, with games on <strong>Microsoft</strong> consoles and having large console availability as reference, we can see that:</p>
<ul>
<li><p>For <strong>Microsoft</strong>,</p>
<ul>
<li><p>While keeping critic score constant, compared to sales of game on large number of consoles, estimated sales <strong>decreases 0.299</strong> million USD when games run on <strong>medium</strong> number of consoles and <strong>decreases 0.265</strong> million USD when games run on <strong>small</strong> number of consoles;</p></li>
<li><p>While keeping console availability constant, the estimated total sales <strong>increases 0.228</strong> million USD for one unit increase in <strong>critic score</strong> on average.</p></li>
</ul></li>
<li><p>For <strong>Nintendo</strong>,</p>
<ul>
<li><p>While keeping critic score constant, compared to sales of <strong>Microsoft</strong> game with same level of console availability, estimated sales <strong>increases 0.476</strong> million USD for <strong>Nintendo</strong> games with <strong>large</strong> number of consoles, <strong>increases 0.691</strong> million USD for games with <strong>medium</strong> number of consoles, and <strong>increases 0.789</strong> million USD for games with <strong>small</strong> number of consoles;</p></li>
<li><p>Among <strong>Nintendo</strong> games, while keeping critic score constant, there is supposed to be <strong>0.084 million USD decrease</strong> when compared games on <strong>medium</strong> number of platforms with <strong>large</strong> number of platforms, and <strong>0.048 million USD increase</strong> when compared games on <strong>small</strong> number of platforms with <strong>large</strong> number of platforms;</p></li>
<li><p>While keeping console availability constant, the estimated total sales <strong>increases 0.121</strong> million USD for one unit increase in <strong>critic score</strong> on average.</p></li>
</ul></li>
<li><p>For <strong>Sony</strong>,</p>
<ul>
<li><p>While keeping critic score constant, compared to sales of <strong>Microsoft</strong> game with same level of console availability, estimated sales <strong>decreases 0.136</strong> million USD for <strong>Sony</strong> games with <strong>large</strong> number of consoles, <strong>decreases 0.025</strong> million USD for games with <strong>medium</strong> number of consoles, and <strong>decreases 0.21</strong> million USD for games with <strong>small</strong> number of consoles;</p></li>
<li><p>Among <strong>Sony</strong> games, while keeping critic score constant, there is supposed to be <strong>0.324 million USD decrease</strong> when compared games on <strong>medium</strong> number of platforms with <strong>large</strong> number of platforms, and <strong>0.475 million USD increase</strong> when compared games on <strong>small</strong> number of platforms with <strong>large</strong> number of platforms;</p></li>
<li><p>While keeping console availability constant, the estimated total sales <strong>increases 0.271</strong> million USD for one unit increase in <strong>critic score</strong> on average.</p></li>
</ul></li>
</ul>
<p><br></p>
</div>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>From the analysis above, <strong>2008</strong> is the year with the <strong>highest global revenues</strong> and the <strong>most games released</strong>. In 2008, many popular games with high revenues are released in gaming industry such as <em>Grand Theft Auto IV</em> and <em>Mario Kart Wii</em>. After 2008, both cumulative sales and number of games released decrease possibly due to the effects of the 2008 financial recession and the rise in popularity of PC and mobile gaming as technology advances. Another possible reason for the downfall is that the console makers are not eager to release new models as often and game developers are taking longer to develop games as demands for more effort-intensive features increase, which also decreases the number of games published each year. Furthermore, sales of more recently released games may be lower because they are younger than their predecessors.</p>
<p>After 2012, in general, there is a decrease in both the number of games released and total revenues for the three big companies: Nintendo, Sony, and Microsoft.</p>
<p><strong>Action</strong>, <strong>sports</strong>, and <strong>shooting</strong> are the most popular genres that bring the most profits to the companies overall. Not particularly surprising.</p>
<p>It seems that as critic scores increase, there is a generally associated increase in global sales as well. <strong>Sony</strong> is the company in which their games has the <strong>highest critic score</strong> and <strong>highest global sales</strong>.</p>
<p>Platform availability refers to the number of consoles that a game is released on, and running more consoles indicates higher availability (e.g. you can play Grand Theft Auto V on PlayStation 4 or on Xbox One). High availability sometimes indicates high popularity, which is supposed to bring in more sales. However, non-exclusive games won’t encourage people to buy certain consoles, since they can play them on consoles they already have. In this way, the sales brought by the game would be “diluted”.</p>
<p>In order to validate the results of our main findings, an <em>ANOVA test</em> and <em>linear regression</em> are performed. Our statistical analyses confirmed that the critic scores and the number of available platforms per game play a role in influencing the global revenues of each game.</p>
<ul>
<li><strong>Better critic scores</strong> imply <strong>higher game’s sales</strong> on average.</li>
<li>Games released on <strong>higher number of platforms</strong> tend to have <strong>better sales</strong> than the games released on lower number of platforms.</li>
</ul>
<p>There are many limitations to our analyses. First of all, the regression model only includes games with total sale less than 5 million USD and omits those high-earning games that would be significant outliers in the linear regression model. Ideally, we would like to include all games. Also, we built models by hypothesis instead of performing a model selection procedure such as a stepwise method to find the “best” model. The resulting model does not have an ideal distribution of residuals, and the r.square is quite low as well, which indicates that the model should be improved. We also find it difficult to interpret a large model containing all variables since there are too many categorical variables to consider.</p>
<p><br></p>
</div>
<div id="interactive-map" class="section level2">
<h2>Interactive Map</h2>
<div id="top-10-best-selling-video-games" class="section level3">
<h3>1. Top 10 best-selling video games</h3>
<p>Video game preferences tend to shift regularly, but a look at the graph of the top 10 best-selling games of the last 19 years shows how loyal players have remained to some of the industry’s biggest franchises. The bar graph shows the top 10 best-selling video games based on the selection of console developer, genre, and release year range. Overall, from 2001 to 2020, Nintendo holds the top place of total revenues with <em>Wii Sports</em>, dominating the chart with sales of more than 80 million USD.</p>
</div>
<div id="distribution-of-total-sales-by-console" class="section level3">
<h3>2. Distribution of total sales by console</h3>
<p>The second chart is a boxplot showing the distribution of total sales by console. Regardless of console developer, genre, and release year range, the second chart implies that the distribution of total sales is actually very skewed (appearing normal due to a log transformation) by some extremely high-earning games, with centers at around 0.5 million USD or 500,000 USD.</p>
</div>
<div id="total-sales-by-release-year" class="section level3">
<h3>3. Total sales by release year</h3>
<p>The third chart gives the total sales by games’ release year. The highest total sales by release year occur in 2008.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
