---
title: "Scrape game sales - Action genre"
output: github_document
---

```{r}
library(rvest)
library(httr)
library(tidyverse)
```


```{r}
url = "https://www.vgchartz.com/games/games.php?page=1&results=200&genre=Action&order=TotalSales&ownership=Both&direction=DESC&showtotalsales=1&shownasales=1&showpalsales=1&showjapansales=1&showothersales=1&showpublisher=1&showdeveloper=1&showreleasedate=1&showlastupdate=0&showvgchartzscore=0&showcriticscore=0&showuserscore=0&showshipped=0&showmultiplat=Yes"

read_sales_values = function(url) {

html = read_html(url)

titles = 
  html %>% 
  html_nodes("td~ td+ td a:nth-child(1)") %>% 
  html_text()

consoles = 
  html %>% 
  html_nodes("td~ td+ td img") %>% 
  html_attr(., name = "alt") 

publishers =
  html %>% 
  html_nodes("#generalBody td:nth-child(5)") %>% 
  html_text()

developers = 
  html %>% 
  html_nodes("#generalBody td:nth-child(6)") %>% 
  html_text()

total_sales = 
  html %>% 
  html_nodes("td:nth-child(7)") %>% 
  html_text()

na_sales = 
  html %>% 
  html_nodes("td:nth-child(8)") %>% 
  html_text()

pal_sales = 
  html %>% 
  html_nodes("td:nth-child(9)") %>% 
  html_text()

japan_sales =
  html %>% 
  html_nodes("td:nth-child(10)") %>% 
  html_text()

other_sales =
  html %>% 
  html_nodes("td:nth-child(11)") %>% 
  html_text()

release_dates =
  html %>% 
  html_nodes("td:nth-child(12)") %>% 
  html_text()

tibble(
  title = titles,
  console = consoles,
  publisher = publishers,
  developer = developers,
  total_sale = total_sales,
  na_sale = na_sales,
  pal_sale = pal_sales,
  japan_sale = japan_sales,
  other_sale = other_sales,
  release_date = release_dates
)
}
```

We can use this function to read 16 pages 

```{r}
url_base = "https://www.vgchartz.com/games/games.php?page=1&results=200&genre=Action&order=TotalSales&ownership=Both&direction=DESC&showtotalsales=1&shownasales=1&showpalsales=1&showjapansales=1&showothersales=1&showpublisher=1&showdeveloper=1&showreleasedate=1&showlastupdate=0&showvgchartzscore=0&showcriticscore=0&showuserscore=0&showshipped=0&showmultiplat=Yes"

vec_urls = str_c(url_base, 1:16)
```

```{r}
output = vector("list", 16)

for (i in 1:16) {
  output[[i]] = read_sales_values(vec_urls[[i]])
}

sale_values = bind_rows(output)

sale_values = map_df(vec_urls, read_sales_values)
```


```{r}
write_csv(sale_values, "data/action.csv")
```
