---
title: "Webscraping"
date: "11/3/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
```

Scrape the game title, release date, platform, metascore, and user score from all 180 pages:

```{r}
title_vec = c()
platform_vec = c()
release_date_vec = c()
meta_score_vec = c()
user_score_vec = c()

for (i in 0:10) {
url = paste("http://www.metacritic.com/browse/games/score/metascore/all/psvita/filtered?view=detailed&page=", i, sep = "")

metacritic_html = read_html(url)

title =
  metacritic_html %>% 
  html_nodes(".title h3") %>% 
  html_text()
  
title_vec = append(title_vec, title[-1])

platform = 
  metacritic_html %>% 
  html_nodes(".platform .data") %>% 
  html_text() %>% 
  gsub("\n","",.)  %>% 
  gsub("^\\s+|\\s+$","",.) 
  
platform_vec = append(platform_vec,platform)

release_date = 
  metacritic_html %>% 
  html_nodes(".platform+ span") %>% 
  html_text()

release_date_vec = append(release_date_vec,release_date)

meta_score = 
  metacritic_html %>% 
  html_nodes(".clamp-metascore .positive") %>% 
  html_text()

meta_score_vec = append(meta_score_vec,meta_score)

user_score = 
  metacritic_html %>% 
  html_nodes(".user") %>% 
  html_text()

user_score_vec = append(user_score_vec,user_score)
}

```


Create a tibble to store all variables scraped:

```{r}
games_df = tibble(
  title = title_vec,
  platform = platform_vec,
  release_date = release_date_vec,
  meta_score = meta_score_vec,
  user_score = user_score_vec
  )
```


Scrape genre, ESRB rating, and developer from individual game detail pages:

```{r}
developer_vec = c()
genre_vec = c()
esrb_rating_vec = c()

platform_add = tolower(platform_vec) %>% 
  str_replace_all(" ","-")
  
# I think this works too? It's also shorter
title_add = tolower(title_vec) %>%
  str_replace_all("\\ &","") %>%
  str_replace_all(" /","") %>%
  str_replace_all(" :","") %>% 
  str_replace_all("[^[:alnum:][:blank:]-!+]", "") %>%
  str_replace_all(" ","-")

# title_add = tolower(title_vec) %>%
#   str_replace_all(":","") %>%
#    str_replace_all("'","") %>%
#    str_replace_all(" /","") %>%
#    str_replace_all(";","") %>%
#    str_replace_all("\\(","") %>%
#    str_replace_all("\\)","") %>%
#    str_replace_all("\\.","") %>%
#    str_replace_all("\\ &","") %>%
#    str_replace_all("\\$","") %>%
#   str_replace_all(",","") %>%
#    str_replace_all(" ","-")
 
for (i in 1:1100) {
url = paste("https://www.metacritic.com/game",platform_add[i],title_add[i],sep = "/")
  tryCatch({
    detail_html = read_html(url)
    developer = 
      detail_html %>% 
      html_nodes(".developer .data") %>% 
      html_text() %>% 
      ifelse(length(.) == 0, NA, .) %>% 
      gsub("\n","",.)  %>% 
      gsub("^\\s+|\\s+$","",.)
    developer_vec = append(developer_vec,developer)},
    error = function(e) {
      print(i)
      return(NA)}) 

genre = 
  detail_html %>% 
  html_nodes(".product_genre .data") %>% 
  html_text() %>% 
  ifelse(length(.) == 0, NA, .) %>% 
  gsub("\n","",.)

genre_vec = append(genre_vec,genre)

esrb_rating = 
  detail_html %>% 
  html_nodes(".product_rating .data") %>% 
  html_text() %>% 
  ifelse(length(.) == 0, NA, .) %>% 
  gsub("\n","",.)

esrb_rating_vec = append(esrb_rating_vec,esrb_rating)

}

games_df = games_df %>% 
  mutate(developer = developer_vec,
         genre = genre_vec,
         esrb_rating = esrb_rating_vec)

write_csv(games_df, "data/metacritic.csv")

```
