---
title: "Play with our game data!"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

<style>                     
.navbar {
  background-color:black;
  border-color:black;
}
</style> 

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(shiny)
```

```{r}
games_df = read_csv("./games.csv")
```

Options {.sidebar}
-----------------------------------------------------------------------
[Home](https://fw2260.github.io/p8105_final_project/)

Did your favorite games make it to the Top 10? Make your own selections below!

Hover over the various data markers for additional information such as game publisher, game developer, and critic scores.

```{r sidebar}
developer_choices = c("All", unique(sort(games_df$console_developer)))
radioButtons(
  "developer_choice",
  h3("Console Developer"),
  choices = developer_choices, selected = "All"
)

genre_choices = c("All", unique(sort(games_df$genre)))
selectInput(
  "genre_choice",
  h3("Genre Choice"),
  choices = genre_choices,
  selected = "All"
)

sliderInput(
  "year_range",
  h3("Release Year"),
  2001, 2020, 
  value = c(2001, 2020),
  ticks = FALSE,
  sep = "")
```


Column {data-width=650}
-----------------------------------------------------------------------
### Top 10 best-selling video games

```{r}
sub_games_10_df = reactive({
  
  if (input$developer_choice == "All") {
    if (input$genre_choice == "All"){
      games_df
    } else {
      games_df %>% filter(genre == input$genre_choice)
    }
  } else {
    if(input$genre_choice == "All") {
      games_df %>% filter(console_developer == input$developer_choice)
    } else {
      games_df %>% 
        filter(genre == input$genre_choice,
               console_developer == input$developer_choice)
    }
  }
})

renderPlotly({
  sub_games_10_df() %>% 
    filter(
      release_year %in% input$year_range[1]:input$year_range[2] 
    ) %>%   
    arrange(desc(total_sale)) %>% 
  slice(1:10) %>% 
  mutate(id = as.character(row_number()),
         id = fct_reorder(id, total_sale),
         text_label = str_c("Game Developer: ", developer,
                            "\nGame Publisher: ", publisher,
                            "\nCritic Score: ", critic_score)) %>% 
  plot_ly(y = ~total_sale, x = ~id, color = ~console, type = "bar", text = ~text_label) %>% 
      layout(showlegend = T,
        xaxis = list(
          tickvals = ~id,
          ticktext = ~title,
          title = "Game Title",
          titlefont = list(
            family = "Courier New, monospace",
            size = 16,
            color = "#7f7f7f"
        )),
        yaxis = list(
          title = "Total Sale (million $)",
          titlefont = list(
            family = "Courier New, monospace",
            size = 16,
            color = "#7f7f7f"
        )))
})
```

Column {data-width=550}
-----------------------------------------------------------------------

### Distribution of total sales by console (log scale)

```{r}
sub_console_df = reactive({
  
  if (input$developer_choice == "All") {
    if (input$genre_choice == "All"){
      games_df
    } else {
      games_df %>% filter(genre == input$genre_choice)
    }
  } else {
    if(input$genre_choice == "All") {
      games_df %>% filter(console_developer == input$developer_choice)
    } else {
    games_df %>% 
      filter(genre == input$genre_choice,
             console_developer == input$developer_choice)
    }
  }
})

renderPlotly({
  sub_console_df() %>% 
    filter(
    release_year %in% input$year_range[1]:input$year_range[2] 
  ) %>% 
    mutate(console = as.factor(console),
           console = fct_reorder(console, total_sale),
           text_label = str_c("Game Title: ", title,
                              "\nGame Developer: ", developer,
                              "\nGame Publisher: ", publisher,
                              "\nCritic Score: ", critic_score)) %>% 
    plot_ly(x = ~total_sale, y = ~console, color = ~console, type = "box", text = ~text_label) %>% 
    layout(
      xaxis = list(
        type = "log",
        title = "Total Sale (million $)",
        titlefont = list(
          family = "Courier New, monospace",
          size = 14,
          color = "#7f7f7f"
        )),
      yaxis = list(
        title = "Console",
        titlefont = list(
          family = "Courier New, monospace",
          size = 14,
          color = "#7f7f7f"
        )),
      showlegend = FALSE)
})
```

### Total sales by release year

```{r}
sub_games_df = reactive({
  
  if (input$developer_choice == "All") {
    if (input$genre_choice == "All"){
      games_df 
    } else {
      games_df %>% filter(genre == input$genre_choice)
    }
  } else {
    if(input$genre_choice == "All") {
      games_df %>% filter(console_developer == input$developer_choice)
    } else {
      games_df %>% 
      filter(genre == input$genre_choice,
             console_developer == input$developer_choice)
    }
  }
})

renderPlotly({
  sub_games_df() %>%
    group_by(release_year) %>% 
    filter(release_year %in% input$year_range[1]:input$year_range[2]) %>%
    summarize(totalsale = sum(total_sale),
              count = n()) %>%
    mutate(text_label = str_c("Number of games: ", count)) %>%
    plot_ly(x = ~release_year, y = ~totalsale, type = "scatter", mode = "lines", text = ~text_label) %>% 
    layout(
      xaxis = list(
        title = "Release Year",
        titlefont = list(
          family = "Courier New, monospace",
          size = 14,
          color = "#7f7f7f"
        )),
      yaxis = list(
        title = "Total Sale (million $)",
        titlefont = list(
          family = "Courier New, monospace",
          size = 14,
          color = "#7f7f7f"
        )))

})
```